// Code generated by protoc-gen-go.
// source: db_msg.proto
// DO NOT EDIT!

/*
Package db_msg is a generated protocol buffer package.

It is generated from these files:
	db_msg.proto

It has these top-level messages:
	UserTockenReq
	UserTockenResp
*/
package db_msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ----------------------------客户端请求sh--------------------------
// 用户认证，id:1，玩家进入房间，带惟一ID
type UserTockenReq struct {
	Timestamp int64  `protobuf:"varint,1,opt,name=Timestamp" json:"Timestamp,omitempty"`
	UserID    uint64 `protobuf:"varint,2,opt,name=UserID" json:"UserID,omitempty"`
	Token     string `protobuf:"bytes,3,opt,name=Token" json:"Token,omitempty"`
}

func (m *UserTockenReq) Reset()                    { *m = UserTockenReq{} }
func (m *UserTockenReq) String() string            { return proto.CompactTextString(m) }
func (*UserTockenReq) ProtoMessage()               {}
func (*UserTockenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// --------------------------服务端推送------------------------------
// 玩家进入游戏，id=101
type UserTockenResp struct {
	Bsucc bool `protobuf:"varint,1,opt,name=Bsucc" json:"Bsucc,omitempty"`
}

func (m *UserTockenResp) Reset()                    { *m = UserTockenResp{} }
func (m *UserTockenResp) String() string            { return proto.CompactTextString(m) }
func (*UserTockenResp) ProtoMessage()               {}
func (*UserTockenResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*UserTockenReq)(nil), "db_msg.UserTockenReq")
	proto.RegisterType((*UserTockenResp)(nil), "db_msg.UserTockenResp")
}

func init() { proto.RegisterFile("db_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x49, 0x8a, 0xcf,
	0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xa2, 0xb9, 0x78,
	0x43, 0x8b, 0x53, 0x8b, 0x42, 0xf2, 0x93, 0xb3, 0x53, 0xf3, 0x82, 0x52, 0x0b, 0x85, 0x64, 0xb8,
	0x38, 0x43, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98,
	0x83, 0x10, 0x02, 0x42, 0x62, 0x5c, 0x6c, 0x20, 0xe5, 0x9e, 0x2e, 0x12, 0x4c, 0x40, 0x29, 0x96,
	0x20, 0x28, 0x4f, 0x48, 0x84, 0x8b, 0x35, 0x24, 0x1f, 0x68, 0x82, 0x04, 0x33, 0x50, 0x98, 0x33,
	0x08, 0xc2, 0x51, 0x52, 0xe3, 0xe2, 0x43, 0x36, 0xbc, 0xb8, 0x00, 0xa4, 0xce, 0xa9, 0xb8, 0x34,
	0x39, 0x19, 0x6c, 0x32, 0x47, 0x10, 0x84, 0x93, 0xc4, 0x06, 0x76, 0x93, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x64, 0x45, 0xde, 0x74, 0xa3, 0x00, 0x00, 0x00,
}
