// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	UserEntryGameReq
	UserYaZhuReq
	UserExitGameReq
	UserEntryGameResp
	UserYaZhuResp
	GameCaiJinResp
	UserExitGameResp
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ----------------------------客户端请求--------------------------
// 用户认证，id:1，玩家进入房间，带惟一ID
type UserEntryGameReq struct {
	Timestamp   int64  `protobuf:"varint,1,opt,name=Timestamp" json:"Timestamp,omitempty"`
	UserID      uint64 `protobuf:"varint,2,opt,name=UserID" json:"UserID,omitempty"`
	Token       string `protobuf:"bytes,3,opt,name=Token" json:"Token,omitempty"`
	Version     int32  `protobuf:"varint,4,opt,name=Version" json:"Version,omitempty"`
	IsReconnect bool   `protobuf:"varint,5,opt,name=IsReconnect" json:"IsReconnect,omitempty"`
	IP          string `protobuf:"bytes,6,opt,name=IP" json:"IP,omitempty"`
}

func (m *UserEntryGameReq) Reset()                    { *m = UserEntryGameReq{} }
func (m *UserEntryGameReq) String() string            { return proto.CompactTextString(m) }
func (*UserEntryGameReq) ProtoMessage()               {}
func (*UserEntryGameReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 玩家压注(开始游戏)，id:2
type UserYaZhuReq struct {
	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp" json:"Timestamp,omitempty"`
	UserID    int32 `protobuf:"varint,2,opt,name=UserID" json:"UserID,omitempty"`
	CoinNum   int64 `protobuf:"varint,3,opt,name=CoinNum" json:"CoinNum,omitempty"`
}

func (m *UserYaZhuReq) Reset()                    { *m = UserYaZhuReq{} }
func (m *UserYaZhuReq) String() string            { return proto.CompactTextString(m) }
func (*UserYaZhuReq) ProtoMessage()               {}
func (*UserYaZhuReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 玩家退出，id:3  服务器需要清除玩家数据
type UserExitGameReq struct {
	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp" json:"Timestamp,omitempty"`
	UserID    int32 `protobuf:"varint,2,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *UserExitGameReq) Reset()                    { *m = UserExitGameReq{} }
func (m *UserExitGameReq) String() string            { return proto.CompactTextString(m) }
func (*UserExitGameReq) ProtoMessage()               {}
func (*UserExitGameReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// --------------------------服务端推送------------------------------
// 玩家进入游戏，id=101
type UserEntryGameResp struct {
	Bsucc bool `protobuf:"varint,1,opt,name=Bsucc" json:"Bsucc,omitempty"`
}

func (m *UserEntryGameResp) Reset()                    { *m = UserEntryGameResp{} }
func (m *UserEntryGameResp) String() string            { return proto.CompactTextString(m) }
func (*UserEntryGameResp) ProtoMessage()               {}
func (*UserEntryGameResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 玩家压注(开始游戏):102
type UserYaZhuResp struct {
	Timestamp int64   `protobuf:"varint,1,opt,name=Timestamp" json:"Timestamp,omitempty"`
	Chess     []int32 `protobuf:"varint,2,rep,packed,name=Chess" json:"Chess,omitempty"`
	BQuanPan  bool    `protobuf:"varint,3,opt,name=BQuanPan" json:"BQuanPan,omitempty"`
	CoinNum   int64   `protobuf:"varint,4,opt,name=CoinNum" json:"CoinNum,omitempty"`
}

func (m *UserYaZhuResp) Reset()                    { *m = UserYaZhuResp{} }
func (m *UserYaZhuResp) String() string            { return proto.CompactTextString(m) }
func (*UserYaZhuResp) ProtoMessage()               {}
func (*UserYaZhuResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 推送彩金:103
type GameCaiJinResp struct {
	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp" json:"Timestamp,omitempty"`
}

func (m *GameCaiJinResp) Reset()                    { *m = GameCaiJinResp{} }
func (m *GameCaiJinResp) String() string            { return proto.CompactTextString(m) }
func (*GameCaiJinResp) ProtoMessage()               {}
func (*GameCaiJinResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// 退出:104
type UserExitGameResp struct {
	Bsucc bool `protobuf:"varint,1,opt,name=Bsucc" json:"Bsucc,omitempty"`
}

func (m *UserExitGameResp) Reset()                    { *m = UserExitGameResp{} }
func (m *UserExitGameResp) String() string            { return proto.CompactTextString(m) }
func (*UserExitGameResp) ProtoMessage()               {}
func (*UserExitGameResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*UserEntryGameReq)(nil), "msg.UserEntryGameReq")
	proto.RegisterType((*UserYaZhuReq)(nil), "msg.UserYaZhuReq")
	proto.RegisterType((*UserExitGameReq)(nil), "msg.UserExitGameReq")
	proto.RegisterType((*UserEntryGameResp)(nil), "msg.UserEntryGameResp")
	proto.RegisterType((*UserYaZhuResp)(nil), "msg.UserYaZhuResp")
	proto.RegisterType((*GameCaiJinResp)(nil), "msg.GameCaiJinResp")
	proto.RegisterType((*UserExitGameResp)(nil), "msg.UserExitGameResp")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0xcd, 0x8f, 0xc9, 0xa8, 0x55, 0x17, 0x91, 0x45, 0x3c, 0x94, 0x3d, 0xd5, 0x4b, 0x2f,
	0xbe, 0x41, 0xa3, 0x94, 0x78, 0x90, 0xba, 0x54, 0x41, 0x0f, 0xc2, 0x1a, 0x16, 0xbb, 0x48, 0x76,
	0x63, 0x36, 0x01, 0xfb, 0x4a, 0x3e, 0xa5, 0x93, 0xa4, 0x8d, 0x51, 0x50, 0xd1, 0xdb, 0x7e, 0xdf,
	0x24, 0xf3, 0xfd, 0x30, 0x10, 0x65, 0xf6, 0x69, 0x92, 0x17, 0xa6, 0x34, 0xc4, 0xc5, 0x27, 0x7b,
	0x73, 0x60, 0xff, 0xc6, 0xca, 0xe2, 0x42, 0x97, 0xc5, 0x6a, 0x26, 0x32, 0xc9, 0xe5, 0x0b, 0x39,
	0x81, 0x68, 0xa1, 0x32, 0x69, 0x4b, 0x91, 0xe5, 0xd4, 0x19, 0x39, 0x63, 0x97, 0x7f, 0x10, 0xe4,
	0x08, 0x82, 0xfa, 0x8f, 0xe4, 0x9c, 0x0e, 0x70, 0xe4, 0xf1, 0x35, 0x22, 0x87, 0xe0, 0x2f, 0xcc,
	0xb3, 0xd4, 0xd4, 0x45, 0x3a, 0xe2, 0x2d, 0x20, 0x14, 0xb6, 0x6e, 0x65, 0x61, 0x95, 0xd1, 0xd4,
	0x43, 0xde, 0xe7, 0x1b, 0x48, 0x46, 0xb0, 0x9d, 0x58, 0x2e, 0x53, 0xa3, 0xb5, 0x4c, 0x4b, 0xea,
	0xe3, 0x34, 0xe4, 0x7d, 0x8a, 0x0c, 0x61, 0x90, 0xcc, 0x69, 0xd0, 0xac, 0xc3, 0x17, 0x7b, 0x80,
	0x9d, 0x5a, 0xeb, 0x4e, 0xdc, 0x2f, 0xab, 0xbf, 0xfa, 0xf4, 0x3b, 0x9f, 0xe8, 0x28, 0x36, 0x4a,
	0x5f, 0x55, 0x59, 0xe3, 0xd4, 0xe5, 0x1b, 0xc8, 0x66, 0xb0, 0xd7, 0x74, 0xf1, 0xaa, 0xca, 0xff,
	0x54, 0xd1, 0x49, 0xb0, 0x53, 0x38, 0xf8, 0x52, 0xaa, 0xcd, 0xeb, 0x7e, 0xa6, 0xb6, 0x4a, 0xd3,
	0x66, 0x4d, 0xc8, 0x5b, 0xc0, 0x56, 0xb0, 0xdb, 0xcb, 0x84, 0x9f, 0xfd, 0xac, 0x88, 0x4b, 0xe2,
	0xa5, 0xb4, 0x16, 0x05, 0x5d, 0x14, 0x6c, 0x01, 0x39, 0x86, 0x70, 0x7a, 0x5d, 0x09, 0x3d, 0x17,
	0x6d, 0xfb, 0x21, 0xef, 0x70, 0x3f, 0xae, 0xf7, 0x39, 0xee, 0x04, 0x86, 0xb5, 0xb9, 0x58, 0xa8,
	0x4b, 0xa5, 0x7f, 0xd7, 0x66, 0xe3, 0xf5, 0xa9, 0x74, 0xf5, 0x7c, 0x17, 0xea, 0x31, 0x68, 0x2e,
	0xec, 0xec, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x03, 0xa4, 0xca, 0xf8, 0x6e, 0x02, 0x00, 0x00,
}
